services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    volumes:
      - wordpress_data:/var/www/html
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/casper/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/casper/data/wordpress_data

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt