services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    image: nginx
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    image: mariadb
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    image: wordpress
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/casper/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/casper/data/wordpress_data

networks:
  inception:
    name: inception